name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: VARIABLES DE ENTORNO
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        DOMINIO: franhv.surge.sh
    - name: Install surge and fire deployment
      uses: actions/setup-node@v1
      with:
        node-version: 8
    - run: npm install -g surge
    - name: Run surge
      run: surge ./_build $DOMINIO --token $SURGE_TOKEN

